// Nomes de países em INGLÊS por código FIFA (3 letras) — usados para casar com o
// TheSportsDB (all_leagues.php), cujo campo strCountry é em inglês.
export const FIFA_CODE_TO_EN: Record<string, string> = {
  AFG: "Afghanistan", AIA: "Anguilla", ALB: "Albania", ALG: "Algeria",
  AND: "Andorra", ANG: "Angola", ARG: "Argentina", ARM: "Armenia", ARU: "Aruba",
  ASA: "American Samoa", ATG: "Antigua and Barbuda", AUS: "Australia", AUT: "Austria",
  AZE: "Azerbaijan", BAH: "Bahamas", BAN: "Bangladesh", BDI: "Burundi", BEL: "Belgium",
  BEN: "Benin", BER: "Bermuda", BFA: "Burkina Faso", BHR: "Bahrain", BHU: "Bhutan",
  BIH: "Bosnia and Herzegovina", BLR: "Belarus", BLZ: "Belize", BOE: "Bonaire",
  BOL: "Bolivia", BOT: "Botswana", BRA: "Brazil", BRB: "Barbados", BRU: "Brunei",
  BUL: "Bulgaria", CAN: "Canada", CAY: "Cayman Islands", CHA: "Chad", CHI: "Chile",
  CHN: "China", CIV: "Ivory Coast", CMR: "Cameroon", COD: "DR Congo", COG: "Congo",
  COK: "Cook Islands", COL: "Colombia", COM: "Comoros", CPV: "Cape Verde",
  CRC: "Costa Rica", CRO: "Croatia", CTA: "Central African Republic", CUB: "Cuba",
  CUW: "Curacao", CYP: "Cyprus", CZE: "Czech Republic", DEN: "Denmark", DJI: "Djibouti",
  DMA: "Dominica", DOM: "Dominican Republic", ECU: "Ecuador", EGY: "Egypt", ENG: "England",
  ERI: "Eritrea", ESP: "Spain", EST: "Estonia", ETH: "Ethiopia", FIJ: "Fiji",
  FIN: "Finland", FRA: "France", FRO: "Faroe Islands", FSM: "Micronesia", GAB: "Gabon",
  GEO: "Georgia", GER: "Germany", GHA: "Ghana", GIB: "Gibraltar", GIN: "Guinea",
  GLP: "Guadeloupe", GMB: "Gambia", GNB: "Guinea-Bissau", GNQ: "Equatorial Guinea",
  GRE: "Greece", GRN: "Grenada", GUA: "Guatemala", GUF: "French Guiana", GUM: "Guam",
  GUY: "Guyana", HAI: "Haiti", HKG: "Hong Kong", HON: "Honduras", HUN: "Hungary",
  IDN: "Indonesia", IND: "India", IRL: "Ireland", IRN: "Iran", IRQ: "Iraq",
  ISL: "Iceland", ISR: "Israel", ISV: "US Virgin Islands", ITA: "Italy",
  IVB: "British Virgin Islands", JAM: "Jamaica", JOR: "Jordan", JPN: "Japan",
  KAZ: "Kazakhstan", KEN: "Kenya", KGZ: "Kyrgyzstan", KHM: "Cambodia", KIR: "Kiribati",
  KOR: "South Korea", KOS: "Kosovo", KSA: "Saudi Arabia", KUW: "Kuwait", LAO: "Laos",
  LBN: "Lebanon", LBR: "Liberia", LBY: "Libya", LCA: "Saint Lucia", LIE: "Liechtenstein",
  LKA: "Sri Lanka", LSO: "Lesotho", LTU: "Lithuania", LUX: "Luxembourg", LVA: "Latvia",
  MAC: "Macau", MAD: "Madagascar", MAR: "Morocco", MAS: "Malaysia", MDA: "Moldova",
  MDV: "Maldives", MEX: "Mexico", MKD: "North Macedonia", MLI: "Mali", MLT: "Malta",
  MMR: "Myanmar", MNE: "Montenegro", MNG: "Mongolia", MOZ: "Mozambique",
  MRT: "Mauritania", MSR: "Montserrat", MTQ: "Martinique", MUS: "Mauritius",
  MWI: "Malawi", NAM: "Namibia", NCA: "Nicaragua", NCL: "New Caledonia",
  NED: "Netherlands", NEP: "Nepal", NER: "Niger", NGA: "Nigeria",
  NIR: "Northern Ireland", NIU: "Niue", NOR: "Norway", NZL: "New Zealand",
  OMA: "Oman", PAK: "Pakistan", PAN: "Panama", PAR: "Paraguay", PER: "Peru",
  PHI: "Philippines", PLW: "Palau", PNG: "Papua New Guinea", POL: "Poland",
  POR: "Portugal", PRK: "North Korea", PUR: "Puerto Rico", QAT: "Qatar",
  ROU: "Romania", RSA: "South Africa", RUS: "Russia", RWA: "Rwanda", SAM: "Samoa",
  SCO: "Scotland", SDN: "Sudan", SEN: "Senegal", SEY: "Seychelles", SGP: "Singapore",
  SKN: "Saint Kitts and Nevis", SLE: "Sierra Leone", SLV: "El Salvador",
  SMA: "Sint Maarten", SMN: "Saint Martin", SMR: "San Marino", SOL: "Solomon Islands",
  SOM: "Somalia", SRB: "Serbia", SSD: "South Sudan", STP: "Sao Tome and Principe",
  SUI: "Switzerland", SUR: "Suriname", SVK: "Slovakia", SVN: "Slovenia",
  SWE: "Sweden", SWZ: "Eswatini", SYR: "Syria", TAH: "Tahiti",
  TCA: "Turks and Caicos Islands", TGA: "Tonga", TGO: "Togo", THA: "Thailand",
  TJK: "Tajikistan", TKM: "Turkmenistan", TLS: "Timor-Leste", TPE: "Chinese Taipei",
  TTO: "Trinidad and Tobago", TUN: "Tunisia", TUR: "Turkey", TUV: "Tuvalu",
  TZA: "Tanzania", UAE: "United Arab Emirates", UGA: "Uganda", UKR: "Ukraine",
  URU: "Uruguay", USA: "United States", UZB: "Uzbekistan", VAN: "Vanuatu",
  VEN: "Venezuela", VIE: "Vietnam", VIN: "Saint Vincent and the Grenadines",
  WAL: "Wales", YEM: "Yemen", ZMB: "Zambia", ZWE: "Zimbabwe",
};
