// Lista CURADA de ligas principais por código FIFA (3 letras) e nível da divisão,
// mapeadas para o título exato da página no Wikipedia (inglês). Usada pelo
// seed-division-logos para baixar os logos REAIS. Divisões fora desta lista ficam
// sem logo (não inventamos nem colocamos logo errado).
export const CURATED_LEAGUE_LOGOS: Record<string, Record<string, string>> = {
  // ---- CONMEBOL ----
  BRA: { "1": "Campeonato Brasileiro Série A", "2": "Campeonato Brasileiro Série B" },
  ARG: { "1": "Argentine Primera División", "2": "Primera Nacional" },
  URU: { "1": "Uruguayan Primera División" },
  CHI: { "1": "Chilean Primera División", "2": "Primera B de Chile" },
  COL: { "1": "Categoría Primera A", "2": "Categoría Primera B" },
  PER: { "1": "Peruvian Primera División" },
  ECU: { "1": "Ecuadorian Serie A" },
  PAR: { "1": "Paraguayan Primera División" },
  BOL: { "1": "Bolivian Primera División" },
  VEN: { "1": "Venezuelan Primera División" },

  // ---- UEFA ----
  ENG: { "1": "Premier League", "2": "EFL Championship" },
  ESP: { "1": "La Liga", "2": "Segunda División" },
  ITA: { "1": "Serie A", "2": "Serie B" },
  GER: { "1": "Bundesliga", "2": "2. Bundesliga" },
  FRA: { "1": "Ligue 1", "2": "Ligue 2" },
  POR: { "1": "Primeira Liga", "2": "Liga Portugal 2" },
  NED: { "1": "Eredivisie", "2": "Eerste Divisie" },
  BEL: { "1": "Belgian Pro League", "2": "Challenger Pro League" },
  SUI: { "1": "Swiss Super League", "2": "Swiss Challenge League" },
  AUT: { "1": "Austrian Football Bundesliga", "2": "2. Liga (Austria)" },
  SCO: { "1": "Scottish Premiership", "2": "Scottish Championship" },
  GRE: { "1": "Super League Greece", "2": "Super League Greece 2" },
  TUR: { "1": "Süper Lig", "2": "TFF First League" },
  RUS: { "1": "Russian Premier League", "2": "Russian First League" },
  UKR: { "1": "Ukrainian Premier League", "2": "Ukrainian First League" },
  CRO: { "1": "Croatian Football League", "2": "First Football League (Croatia)" },
  SRB: { "1": "Serbian SuperLiga", "2": "Serbian First League" },
  CZE: { "1": "Czech First League", "2": "Czech National Football League" },
  POL: { "1": "Ekstraklasa", "2": "I liga" },
  DEN: { "1": "Danish Superliga", "2": "1st Division (Denmark)" },
  SWE: { "1": "Allsvenskan", "2": "Superettan" },
  NOR: { "1": "Eliteserien", "2": "1. divisjon" },
  FIN: { "1": "Veikkausliiga", "2": "Ykkösliiga" },
  ISL: { "1": "Besta deild karla" },
  IRL: { "1": "League of Ireland Premier Division", "2": "League of Ireland First Division" },
  HUN: { "1": "Nemzeti Bajnokság I", "2": "Nemzeti Bajnokság II" },
  ROU: { "1": "Liga I", "2": "Liga II" },
  BUL: { "1": "First Professional Football League (Bulgaria)", "2": "Second Professional Football League (Bulgaria)" },
  SVK: { "1": "Slovak First Football League", "2": "2. Liga (Slovakia)" },
  SVN: { "1": "Slovenian PrvaLiga" },
  MNE: { "1": "Montenegrin First League" },
  MKD: { "1": "Macedonian First Football League" },
  BIH: { "1": "Premier League of Bosnia and Herzegovina" },
  ALB: { "1": "Kategoria Superiore", "2": "Kategoria e Parë" },
  KOS: { "1": "Football Superleague of Kosovo" },
  ISR: { "1": "Israeli Premier League", "2": "Liga Leumit" },
  CYP: { "1": "Cypriot First Division", "2": "Cypriot Second Division" },
  GEO: { "1": "Erovnuli Liga" },
  ARM: { "1": "Armenian Premier League" },
  AZE: { "1": "Azerbaijan Premier League" },
  KAZ: { "1": "Kazakhstan Premier League" },
  LUX: { "1": "Luxembourg National Division" },
  MLT: { "1": "Maltese Premier League" },
  WAL: { "1": "Cymru Premier" },
  NIR: { "1": "NIFL Premiership" },
  EST: { "1": "Meistriliiga" },
  LVA: { "1": "Latvian Higher League" },
  LTU: { "1": "A Lyga" },
  MDA: { "1": "Moldovan Super Liga" },
  FRO: { "1": "Faroe Islands Premier League" },
  AND: { "1": "Primera Divisió" },
  SMR: { "1": "Campionato Sammarinese di Calcio" },
  GIB: { "1": "Gibraltar Football League" },

  // ---- AFC ----
  JPN: { "1": "J1 League", "2": "J2 League" },
  KOR: { "1": "K League 1", "2": "K League 2" },
  CHN: { "1": "Chinese Super League", "2": "China League One" },
  KSA: { "1": "Saudi Pro League" },
  UAE: { "1": "UAE Pro League" },
  QAT: { "1": "Qatar Stars League" },
  IRN: { "1": "Persian Gulf Pro League" },
  IRQ: { "1": "Iraq Stars League" },
  AUS: { "1": "A-League Men" },
  IND: { "1": "Indian Super League" },
  THA: { "1": "Thai League 1" },
  VIE: { "1": "V.League 1" },
  MAS: { "1": "Malaysia Super League" },
  IDN: { "1": "Liga 1 (Indonesia)" },
  UZB: { "1": "Uzbekistan Super League" },
  SIN: { "1": "Singapore Premier League" },
  HKG: { "1": "Hong Kong Premier League" },
  TPE: { "1": "Taiwan Football Premier League" },
  JOR: { "1": "Jordanian Pro League" },
  BHR: { "1": "Bahraini Premier League" },
  OMA: { "1": "Oman Professional League" },
  KUW: { "1": "Kuwait Premier League" },

  // ---- CAF ----
  EGY: { "1": "Egyptian Premier League" },
  MAR: { "1": "Botola" },
  TUN: { "1": "Tunisian Ligue Professionnelle 1" },
  ALG: { "1": "Algerian Ligue Professionnelle 1" },
  NGA: { "1": "Nigeria Premier Football League" },
  RSA: { "1": "Premier Soccer League" },
  GHA: { "1": "Ghana Premier League" },
  SEN: { "1": "Ligue 1 (Senegal)" },
  CIV: { "1": "Ligue 1 (Ivory Coast)" },
  COD: { "1": "Linafoot" },
  CMR: { "1": "Elite One" },
  ZIM: { "1": "Zimbabwe Premier Soccer League" },
  KEN: { "1": "Kenyan Premier League" },

  // ---- CONCACAF ----
  USA: { "1": "Major League Soccer", "2": "USL Championship" },
  MEX: { "1": "Liga MX", "2": "Liga de Expansión MX" },
  CAN: { "1": "Canadian Premier League" },
  CRC: { "1": "Liga FPD" },
  HON: { "1": "Liga Nacional de Fútbol de Honduras" },
  GUA: { "1": "Liga Nacional de Fútbol de Guatemala" },
  SLV: { "1": "Primera División de El Salvador" },
  PAN: { "1": "Liga Panameña de Fútbol" },
  JAM: { "1": "Jamaica Premier League" },
  TRI: { "1": "TT Premier Football League" },
  HAI: { "1": "Ligue Haïtienne" },

  // ---- OFC ----
  NZL: { "1": "New Zealand National League" },
  FIJ: { "1": "Fiji Premier League" },
  PNG: { "1": "Papua New Guinea National Soccer League" },
  VAN: { "1": "Port Vila Premier League" },
};
