export interface Datapack {
  id: string;
  name: string;
  shortName: string;
  country: string;
  countryCode: string;
  confederation: string;
  wikiUrl: string;
  numTeams: number;
  promoted: number;
  relegated: number;
  format: string;
  emoji: string;
}

export const LEAGUE_DATAPACKS: Datapack[] = [
  // === CONMEBOL ===
  {
    id: "equador-serie-a",
    name: "Campeonato Equatoriano de Futebol",
    shortName: "LigaPro Serie A",
    country: "Equador",
    countryCode: "EC",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Equatoriano_de_Futebol",
    numTeams: 16,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇪🇨",
  },
  {
    id: "brasil-serie-a",
    name: "Campeonato Brasileiro Serie A",
    shortName: "Brasileirao Serie A",
    country: "Brasil",
    countryCode: "BR",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Brasileiro_de_Futebol_-_Serie_A",
    numTeams: 20,
    promoted: 4,
    relegated: 4,
    format: "round-robin",
    emoji: "🇧🇷",
  },
  {
    id: "brasil-serie-b",
    name: "Campeonato Brasileiro Serie B",
    shortName: "Brasileirao Serie B",
    country: "Brasil",
    countryCode: "BR",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Brasileiro_de_Futebol_-_Serie_B",
    numTeams: 20,
    promoted: 4,
    relegated: 4,
    format: "round-robin",
    emoji: "🇧🇷",
  },
  {
    id: "argentina-liga-profesional",
    name: "Liga Profesional de Futbol",
    shortName: "Liga Argentina",
    country: "Argentina",
    countryCode: "AR",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Primera_Division_Argentina",
    numTeams: 30,
    promoted: 0,
    relegated: 0,
    format: "round-robin",
    emoji: "🇦🇷",
  },
  {
    id: "uruguai-primera",
    name: "Primera Division do Uruguai",
    shortName: "Primeira Divisão Uruguaia",
    country: "Uruguai",
    countryCode: "UY",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Uruguaio_de_Futebol",
    numTeams: 16,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇺🇾",
  },
  {
    id: "chile-primera",
    name: "Primera Division do Chile",
    shortName: "Primeira Divisao Chilena",
    country: "Chile",
    countryCode: "CL",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Chileno_de_Futebol",
    numTeams: 16,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇨🇱",
  },
  {
    id: "colombia-primera-a",
    name: "Campeonato Colombiano de Futebol",
    shortName: "Liga BetPlay",
    country: "Colombia",
    countryCode: "CO",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Colombiano_de_Futebol",
    numTeams: 20,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇨🇴",
  },
  {
    id: "peru-liga-1",
    name: "Campeonato Peruano de Futebol",
    shortName: "Liga 1 Peru",
    country: "Peru",
    countryCode: "PE",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Peruano_de_Futebol",
    numTeams: 18,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇵🇪",
  },
  {
    id: "paraguai-primera",
    name: "Campeonato Paraguaio de Futebol",
    shortName: "Primera Division PY",
    country: "Paraguai",
    countryCode: "PY",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Paraguayo_de_Futebol",
    numTeams: 12,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇵🇾",
  },
  {
    id: "bolivia-primera",
    name: "Campeonato Boliviano de Futebol",
    shortName: "División Profesional",
    country: "Bolivia",
    countryCode: "BO",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Boliviano_de_Futebol",
    numTeams: 16,
    promoted: 1,
    relegated: 1,
    format: "round-robin",
    emoji: "🇧🇴",
  },
  {
    id: "venezuela-primera",
    name: "Campeonato Venezuelano de Futebol",
    shortName: "Primeira Divisao VEN",
    country: "Venezuela",
    countryCode: "VE",
    confederation: "CONMEBOL",
    wikiUrl: "https://pt.wikipedia.org/wiki/Campeonato_Venezuelano_de_Futebol",
    numTeams: 14,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇻🇪",
  },

  // === UEFA ===
  {
    id: "inglaterra-premier-league",
    name: "Premier League",
    shortName: "Premier League",
    country: "Inglaterra",
    countryCode: "GB-ENG",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/Premier_League",
    numTeams: 20,
    promoted: 3,
    relegated: 3,
    format: "round-robin",
    emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  },
  {
    id: "espanha-la-liga",
    name: "La Liga",
    shortName: "La Liga",
    country: "Espanha",
    countryCode: "ES",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/La_Liga",
    numTeams: 20,
    promoted: 3,
    relegated: 3,
    format: "round-robin",
    emoji: "🇪🇸",
  },
  {
    id: "italia-serie-a",
    name: "Serie A da Italia",
    shortName: "Serie A",
    country: "Italia",
    countryCode: "IT",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/Serie_A",
    numTeams: 20,
    promoted: 3,
    relegated: 3,
    format: "round-robin",
    emoji: "🇮🇹",
  },
  {
    id: "alemanha-bundesliga",
    name: "Bundesliga",
    shortName: "Bundesliga",
    country: "Alemanha",
    countryCode: "DE",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/Bundesliga",
    numTeams: 18,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇩🇪",
  },
  {
    id: "franca-ligue-1",
    name: "Ligue 1",
    shortName: "Ligue 1",
    country: "Franca",
    countryCode: "FR",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/Ligue_1",
    numTeams: 18,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇫🇷",
  },
  {
    id: "portugal-primeira-liga",
    name: "Primeira Liga",
    shortName: "Liga Portugal",
    country: "Portugal",
    countryCode: "PT",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/Primeira_Liga",
    numTeams: 18,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇵🇹",
  },
  {
    id: "paises-baixos-eredivisie",
    name: "Eredivisie",
    shortName: "Eredivisie",
    country: "Paises Baixos",
    countryCode: "NL",
    confederation: "UEFA",
    wikiUrl: "https://pt.wikipedia.org/wiki/Eredivisie",
    numTeams: 18,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇳🇱",
  },

  // === CONCACAF ===
  {
    id: "eua-mls",
    name: "Major League Soccer",
    shortName: "MLS",
    country: "Estados Unidos",
    countryCode: "US",
    confederation: "CONCACAF",
    wikiUrl: "https://pt.wikipedia.org/wiki/Major_League_Soccer",
    numTeams: 30,
    promoted: 0,
    relegated: 0,
    format: "round-robin",
    emoji: "🇺🇸",
  },
  {
    id: "mexico-liga-mx",
    name: "Liga MX",
    shortName: "Liga MX",
    country: "Mexico",
    countryCode: "MX",
    confederation: "CONCACAF",
    wikiUrl: "https://pt.wikipedia.org/wiki/Liga_MX",
    numTeams: 18,
    promoted: 0,
    relegated: 0,
    format: "round-robin",
    emoji: "🇲🇽",
  },

  // === AFC ===
  {
    id: "japao-j1-league",
    name: "J1 League",
    shortName: "J-League",
    country: "Japao",
    countryCode: "JP",
    confederation: "AFC",
    wikiUrl: "https://pt.wikipedia.org/wiki/J1_League",
    numTeams: 20,
    promoted: 3,
    relegated: 3,
    format: "round-robin",
    emoji: "🇯🇵",
  },
  {
    id: "coreia-sul-k-league",
    name: "K League 1",
    shortName: "K-League",
    country: "Coreia do Sul",
    countryCode: "KR",
    confederation: "AFC",
    wikiUrl: "https://pt.wikipedia.org/wiki/K_League",
    numTeams: 12,
    promoted: 2,
    relegated: 2,
    format: "round-robin",
    emoji: "🇰🇷",
  },
  {
    id: "arabia-saudita-spl",
    name: "Saudi Pro League",
    shortName: "Saudi League",
    country: "Arabia Saudita",
    countryCode: "SA",
    confederation: "AFC",
    wikiUrl: "https://pt.wikipedia.org/wiki/Saudi_Pro_League",
    numTeams: 18,
    promoted: 3,
    relegated: 3,
    format: "round-robin",
    emoji: "🇸🇦",
  },
];